export { default as Main } from './Main/Main';
export { default as Login } from './Auth/Login';
export { default as Regist } from './Auth/Regist';
export { default as Curriculum } from './Curriculum/Curriculum';
export { default as Assignment } from './Assignment/Assignment';
export { default as Board } from './Board/Board';
export { default as Post } from './Post/Post';
export { default as LoginContainer } from './Container/LoginContainer';
export { default as NavContainer } from './Container/NavContainer';